jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2.3.4
    - continue-on-error: true
      name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: '17'
    - continue-on-error: true
      name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1.0.4
    - continue-on-error: true
      name: Build
      run: bash gradlew assembleRelease lintRelease testDebugUnitTest
name: Build App
on:
  repository_dispatch:
    types: trigger-ga___build.yml
